# Generated by Django 3.2.9 on 2022-01-09 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prescription',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.prescription'),
        ),
    ]
