# Generated by Django 3.2.9 on 2021-12-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_orderitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='covid',
            name='no_of_days',
            field=models.IntegerField(null=True),
        ),
    ]
