# Generated by Django 3.2.9 on 2022-01-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220109_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='images',
        ),
        migrations.AddField(
            model_name='prescription',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
