# Generated by Django 3.2.9 on 2021-12-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_covid_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covid',
            name='address',
        ),
    ]
